INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Jump", "Fun", 1/23/2000, 3/23/2000);
INSERT INTO users (id, name, age) VALUES (1, "George", 34);
INSERT INTO users (id, name, age) VALUES (2, "George", 34);
INSERT INTO users (id, name, age) VALUES (3, "George", 34);
INSERT INTO users (id, name, age) VALUES (4, "George", 34);
INSERT INTO users (id, name, age) VALUES (5, "George", 34);
INSERT INTO users (id, name, age) VALUES (6, "George", 34);
INSERT INTO users (id, name, age) VALUES (7, "George", 34);
INSERT INTO users (id, name, age) VALUES (8, "George", 34);
INSERT INTO users (id, name, age) VALUES (9, "George", 34);
INSERT INTO users (id, name, age) VALUES (10, "George", 34);
INSERT INTO users (id, name, age) VALUES (11, "George", 34);
INSERT INTO users (id, name, age) VALUES (12, "George", 34);
INSERT INTO users (id, name, age) VALUES (13, "George", 34);
INSERT INTO users (id, name, age) VALUES (14, "George", 34);
INSERT INTO users (id, name, age) VALUES (15, "George", 34);
INSERT INTO users (id, name, age) VALUES (16, "George", 34);
INSERT INTO users (id, name, age) VALUES (17, "George", 34);
INSERT INTO users (id, name, age) VALUES (18, "George", 34);
INSERT INTO users (id, name, age) VALUES (19, "George", 34);
INSERT INTO users (id, name, age) VALUES (20, "George", 34);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (1, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (2, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (3, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (4, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (5, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (6, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (7, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (8, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (9, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (10, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (11, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (12, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (13, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (14, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (15, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (16, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (17, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (18, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (19, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (20, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (21, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (22, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (23, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (24, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (25, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (26, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (27, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (28, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (29, 30000, 3, 4);
INSERT INTO pledges (id, amount, project_id, user_id) VALUES (30, 30000, 3, 4);